LOG_DIR: 'logs'
EXP_NAME: '18.09-lmdb_test'
METHOD: 'spin'
RUN_TEST: False
PROJECT_NAME: 'pare'
DATASET:
  LOAD_TYPE: 'Base'
  NOISE_FACTOR: 0.4
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  CROP_PROB: 0.0
  CROP_FACTOR: 0.0
  BATCH_SIZE: 64
  NUM_WORKERS: 16
  PIN_MEMORY: True
  SHUFFLE_TRAIN: True
  TRAIN_DS: 'all'
  VAL_DS: '3dpw'
  NUM_IMAGES: -1
  IMG_RES: 224
  FOCAL_LENGTH: 5000.
  USE_SYNTHETIC_OCCLUSION: false
OPTIMIZER:
  TYPE: 'adam'
  LR: 5e-5
  WD: 0.0
TRAINING:
  RESUME: null
  PRETRAINED: null
  PRETRAINED_LIT: null
  MAX_EPOCHS: 100
  LOG_SAVE_INTERVAL: 40
  LOG_FREQ_TB_IMAGES: 500
  CHECK_VAL_EVERY_N_EPOCH: 1
  RELOAD_DATALOADERS_EVERY_EPOCH: True
PARE:
  BACKBONE: 'resnet50'
  NUM_JOINTS: 24
  SOFTMAX_TEMP: 1.
  NUM_FEATURES_SMPL: 64
  USE_SELF_ATTENTION: False
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
SPIN:
  BACKBONE: 'resnet50'
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
TESTING:
  SAVE_IMAGES: false
  SIDEVIEW: true