LOG_DIR: 'logs/'
EXP_NAME: '25.09-pare_heatmap_all_datasets_fixed'
METHOD: 'pare'
RUN_TEST: False
PROJECT_NAME: 'pare'
DATASET:
  LOAD_TYPE: 'LMDB'
  NOISE_FACTOR: 0.4
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  CROP_PROB: 0.0
  CROP_FACTOR: 0.5
  BATCH_SIZE: 64
  NUM_WORKERS: 16
  PIN_MEMORY: True
  SHUFFLE_TRAIN: True
  TRAIN_DS: 'all'
  VAL_DS: '3dpw'
  NUM_IMAGES: -1
  IMG_RES: 224
  FOCAL_LENGTH: 5000.
  IGNORE_3D: False
  USE_HEATMAPS: 'hm'
  USE_SYNTHETIC_OCCLUSION: true
  DATASETS_AND_RATIOS:
    - 'h36m_mpii_lspet_coco_mpi-inf-3dhp_0.3_0.6_0.6_0.6_0.1'
    - 'h36m_mpii_lspet_coco_mpi-inf-3dhp_3doh_0.1_0.6_0.6_0.6_0.1_0.2'
OPTIMIZER:
  TYPE: 'adam'
  LR: 5e-5
  WD: 0.0
TRAINING:
  RESUME: null
  PRETRAINED: null
  PRETRAINED_LIT: 'logs/pare/24.09-pare_heatmap_resume/24-09-2020_20-52-21_24.09-pare_heatmap_resume_train/tb_logs_pare_h36m/0_b8e6eaa134454354a30043be0f8a3599/checkpoints/epoch=52.ckpt'
  MAX_EPOCHS: 100
  SAVE_IMAGES: True
  LOG_SAVE_INTERVAL: 40
  LOG_FREQ_TB_IMAGES: 2000
  CHECK_VAL_EVERY_N_EPOCH: 1
  RELOAD_DATALOADERS_EVERY_EPOCH: True
PARE:
  BACKBONE: 'resnet50'
  NUM_JOINTS: 24
  SOFTMAX_TEMP: 1.
  NUM_FEATURES_SMPL: 64
  USE_SELF_ATTENTION: False
  ITERATIVE_REGRESSION: False
  NUM_ITERATIONS: 3
  SHAPE_INPUT_TYPE: 'feats.shape.cam'
  POSE_INPUT_TYPE: 'feats.self_pose.shape.cam' # ['feats.neighbor_pose_feats.self_pose.shape.cam', 'feats.self_pose.shape.cam', 'feats.self_pose.neighbor_pose.shape.cam', 'feats.neighbor_pose_feats.self_pose.neighbor_pose.shape.cam']
  POSE_MLP_NUM_LAYERS: 1
  SHAPE_MLP_NUM_LAYERS: 1
  POSE_MLP_HIDDEN_SIZE: 256
  SHAPE_MLP_HIDDEN_SIZE: 256
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
  USE_KEYPOINT_FEATURES_FOR_SMPL_REGRESSION: false
SPIN:
  BACKBONE: 'resnet50'
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
TESTING:
  SAVE_IMAGES: false
  SIDEVIEW: true