DATASET:
  BATCH_SIZE: 16
  FOCAL_LENGTH: 5000.0
  IGNORE_3D: false
  IMG_RES: 224
  NOISE_FACTOR: 0.4
  NUM_IMAGES: -1
  NUM_WORKERS: 16
  PIN_MEMORY: true
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  TRAIN_DS: 'all'
  VAL_DS: 'mpii'
EXP_NAME: 'evaluate_spin_mpii'
LOG_DIR: 'logs/'
METHOD: spin
OPTIMIZER:
  LR: 0.0001
  TYPE: adam
  WD: 0.0
PARE:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  NUM_FEATURES_SMPL: 64
  NUM_JOINTS: 24
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
  SOFTMAX_TEMP: 1.0
  USE_SELF_ATTENTION: false
RUN_TEST: false
SPIN:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  LOG_FREQ_TB_IMAGES: 500
  LOG_SAVE_INTERVAL: 40
  MAX_EPOCHS: 100
  NUM_SMPLIFY_ITERS: 100
  RELOAD_DATALOADERS_EVERY_EPOCH: true
  RESUME: null
  PRETRAINED_LIT: '/is/cluster/work/mkocabas/projects/pare/logs/spin/test_all_datasets/07-07-2020_02-31-47_test_all_datasets_training.runsmplify-True/lightning_logs/version_0/checkpoints/epoch=19.ckpt'
  RUN_SMPLIFY: false
  SMPLIFY_THRESHOLD: false
TESTING:
  SAVE_IMAGES: true
  SIDEVIEW: true
