LOG_DIR: 'logs/'
EXP_NAME: '21.09-spin_h36m_uncertainty_test_separate_elu'
METHOD: 'spin'
RUN_TEST: False
PROJECT_NAME: 'pare_h36m'
DATASET:
  NOISE_FACTOR: 0.4
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  BATCH_SIZE: [64]
  NUM_WORKERS: 16
  PIN_MEMORY: True
  SHUFFLE_TRAIN: True
  TRAIN_DS: 'h36m'
  VAL_DS: 'h36m-p2'
  NUM_IMAGES: -1
  IMG_RES: 224
  FOCAL_LENGTH: 5000.
  IGNORE_3D: False
  USE_SYNTHETIC_OCCLUSION: true
OPTIMIZER:
  TYPE: 'adam'
  LR: [5e-05]
  WD: [0.0]
TRAINING:
  RESUME: null
  PRETRAINED: null
  MAX_EPOCHS: 100
  LOG_SAVE_INTERVAL: 40
  LOG_FREQ_TB_IMAGES: 2000
  CHECK_VAL_EVERY_N_EPOCH: 1
  RELOAD_DATALOADERS_EVERY_EPOCH: True
  RUN_SMPLIFY: [False]
  DROPOUT_P: 0.2
TESTING:
  SAVE_IMAGES: False
PARE:
  BACKBONE: 'resnet50'
  NUM_JOINTS: 24
  SOFTMAX_TEMP: [1.]
  NUM_FEATURES_SMPL: [64]
  USE_SELF_ATTENTION: [False]
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: [5.]
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.
SPIN:
  BACKBONE: 'resnet50'
  ESTIMATE_UNCERTAINTY: true
  USE_SEPARATE_VAR_BRANCH: true
  UNCERTAINTY_ACTIVATION: 'elu'
  SHAPE_LOSS_WEIGHT: 0
  KEYPOINT_LOSS_WEIGHT: 5.
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.
  POSE_LOSS_WEIGHT: 1.
  BETA_LOSS_WEIGHT: 0.001
  OPENPOSE_TRAIN_WEIGHT: 0.
  GT_TRAIN_WEIGHT: 1.
  LOSS_WEIGHT: 60.