DATASET:
  BATCH_SIZE: 64
  FOCAL_LENGTH: 5000.0
  IGNORE_3D: false
  IMG_RES: 224
  NOISE_FACTOR: 0.4
  NUM_IMAGES: -1
  NUM_WORKERS: 8
  PIN_MEMORY: true
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  TRAIN_DS: 'all'
  VAL_DS: '3dpw'
EXP_NAME: 'all_datasets_lr_1e05'
LOG_DIR: logs
METHOD: pare
OPTIMIZER:
  LR: 1e-05
  TYPE: adam
  WD: 0.0
PARE:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  NUM_FEATURES_SMPL: 64
  NUM_JOINTS: 24
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
  SOFTMAX_TEMP: 1.0
  USE_SELF_ATTENTION: false
RUN_TEST: false
SPIN:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  LOG_FREQ_TB_IMAGES: 500
  LOG_SAVE_INTERVAL: 40
  MAX_EPOCHS: 100
  NUM_SMPLIFY_ITERS: 100
  RELOAD_DATALOADERS_EVERY_EPOCH: true
  RESUME: null
  PRETRAINED_LIT: 'logs/pare/test_all_datasets/07-07-2020_02-33-14_test_all_datasets_optimizer.lr-5e-05_training.runsmplify-False/lightning_logs/version_0/checkpoints/epoch=54.ckpt'
  RUN_SMPLIFY: false
  SMPLIFY_THRESHOLD: false
