DATASET:
  BATCH_SIZE: 16
  FOCAL_LENGTH: 5000.0
  IGNORE_3D: false
  IMG_RES: 224
  NOISE_FACTOR: 0.4
  NUM_IMAGES: -1
  NUM_WORKERS: 16
  PIN_MEMORY: true
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  TRAIN_DS: 'h36m'
  VAL_DS: 'mpii'
EXP_NAME: 'evaluate_pare_mpii'
LOG_DIR: 'logs/'
METHOD: pare
OPTIMIZER:
  LR: 5.0e-05
  TYPE: adam
  WD: 0.0
PARE:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  NUM_FEATURES_SMPL: 64
  NUM_JOINTS: 24
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
  SOFTMAX_TEMP: 1.0
  USE_SELF_ATTENTION: false
RUN_TEST: false
SPIN:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  LOG_FREQ_TB_IMAGES: 500
  LOG_SAVE_INTERVAL: 40
  MAX_EPOCHS: 100
  NUM_SMPLIFY_ITERS: 100
  RELOAD_DATALOADERS_EVERY_EPOCH: true
  RESUME: null
  PRETRAINED_LIT: '/is/cluster/work/mkocabas/projects/pare/logs/pare/all_datasets_3dpw_3val_small_lr/09-07-2020_23-19-47_all_datasets_3dpw_3val_small_lr_optimizer.lr-5e-05_training.runsmplify-True/lightning_logs/version_0/checkpoints/epoch=5.ckpt'
  RUN_SMPLIFY: true
  SMPLIFY_THRESHOLD: false
TESTING:
  SAVE_IMAGES: true
  SIDEVIEW: true
