EXP_NAME: 06.09-pare_hrnetw32
LOG_DIR: logs
METHOD: pare
PROJECT_NAME: pare
RUN_TEST: false
DATASET:
  BATCH_SIZE: 64
  FOCAL_LENGTH: 5000.0
  IGNORE_3D: false
  IMG_RES: 224
  NOISE_FACTOR: 0.4
  NUM_IMAGES: -1
  NUM_WORKERS: 16
  PIN_MEMORY: true
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  TRAIN_DS: all
  USE_SYNTHETIC_OCCLUSION: true
  VAL_DS: 3dpw
OPTIMIZER:
  LR: 5.0e-05
  TYPE: adam
  WD: 0.0
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  LOG_FREQ_TB_IMAGES: 2000
  LOG_SAVE_INTERVAL: 40
  MAX_EPOCHS: 50
  NUM_SMPLIFY_ITERS: 100
  PRETRAINED: null
  PRETRAINED_LIT: 'logs/pare/04.09-pare_hrnetw32_h36m_pre/04-09-2020_11-29-40_04.09-pare_hrnetw32_h36m_pre/tb_logs_pare_h36m/0_0df3fcbae96d43f4a6e6fac8e98df703/checkpoints/epoch=34.ckpt'
  RELOAD_DATALOADERS_EVERY_EPOCH: true
  RESUME: null
  RUN_SMPLIFY: false
  SMPLIFY_THRESHOLD: 100
PARE:
  BACKBONE: hrnet_w32
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  ITERATIVE_REGRESSION: false
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  NUM_FEATURES_SMPL: 64
  NUM_ITERATIONS: 3
  NUM_JOINTS: 24
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_INPUT_TYPE: feats.self_pose.shape.cam
  POSE_LOSS_WEIGHT: 1.0
  POSE_MLP_HIDDEN_SIZE: 256
  POSE_MLP_NUM_LAYERS: 1
  SHAPE_INPUT_TYPE: feats.shape.cam
  SHAPE_LOSS_WEIGHT: 0
  SHAPE_MLP_HIDDEN_SIZE: 256
  SHAPE_MLP_NUM_LAYERS: 1
  SOFTMAX_TEMP: 1.0
  USE_KEYPOINT_FEATURES_FOR_SMPL_REGRESSION: false
  USE_SELF_ATTENTION: false
SPIN:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
TESTING:
  SAVE_IMAGES: false
  SIDEVIEW: true