DATASET:
  BATCH_SIZE: 64
  CROP_FACTOR: 0.0
  CROP_PROB: 0.0
  FLIP_PROB: 0.5
  FOCAL_LENGTH: 5000.0
  IGNORE_3D: false
  IMG_RES: 224
  LOAD_TYPE: Base
  NOISE_FACTOR: 0.4
  NUM_IMAGES: -1
  NUM_WORKERS: 16
  PIN_MEMORY: true
  RENDER_RES: 480
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  SHUFFLE_TRAIN: true
  TRAIN_DS: h36m
  USE_HEATMAPS: 'hm'
  USE_SYNTHETIC_OCCLUSION: true
  VAL_DS: h36m-p2
EXP_NAME: '23.09-pare_h36m_heatmap_soft_hmweight10'
LOG_DIR: logs/
METHOD: pare
OPTIMIZER:
  LR: 5.0e-05
  TYPE: adam
  WD: 0.0
PARE:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  GT_TRAIN_WEIGHT: 1.0
  ITERATIVE_REGRESSION: false
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  HEATMAPS_LOSS_WEIGHT: 10.0
  LOSS_WEIGHT: 60.0
  NUM_FEATURES_SMPL: 64
  NUM_ITERATIONS: 3
  NUM_JOINTS: 24
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_INPUT_TYPE: feats.self_pose.shape.cam
  POSE_LOSS_WEIGHT: 1.0
  POSE_MLP_HIDDEN_SIZE: 256
  POSE_MLP_NUM_LAYERS: 1
  SHAPE_INPUT_TYPE: feats.shape.cam
  SHAPE_LOSS_WEIGHT: 0
  SHAPE_MLP_HIDDEN_SIZE: 256
  SHAPE_MLP_NUM_LAYERS: 1
  SOFTMAX_TEMP: 1.0
  USE_KEYPOINT_FEATURES_FOR_SMPL_REGRESSION: false
  USE_SELF_ATTENTION: false
PROJECT_NAME: pare_h36m
RUN_TEST: false
SPIN:
  BACKBONE: resnet50
  BETA_LOSS_WEIGHT: 0.001
  ESTIMATE_UNCERTAINTY: false
  GT_TRAIN_WEIGHT: 1.0
  KEYPOINT_LOSS_WEIGHT: 5.0
  KEYPOINT_NATIVE_LOSS_WEIGHT: 5.0
  LOSS_WEIGHT: 60.0
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  SHAPE_LOSS_WEIGHT: 0
  UNCERTAINTY_ACTIVATION: ''
  USE_SEPARATE_VAR_BRANCH: false
SYSTEM:
  GPU: ''
TESTING:
  SAVE_IMAGES: false
  SIDEVIEW: true
TRAINING:
  CHECK_VAL_EVERY_N_EPOCH: 1
  DROPOUT_P: 0.2
  LOG_FREQ_TB_IMAGES: 2000
  LOG_SAVE_INTERVAL: 40
  MAX_EPOCHS: 100
  NUM_SMPLIFY_ITERS: 100
  PRETRAINED: null
  PRETRAINED_LIT: null
  RELOAD_DATALOADERS_EVERY_EPOCH: true
  RESUME: null
  RUN_SMPLIFY: false
  SMPLIFY_THRESHOLD: 100
  TEST_BEFORE_TRAINING: false